#### Week 11 workshop solution for Task 4 for LDA-based clustering 
<author>&copy; Professor Yuefeng Li </author>

Design and implement an LDA-based clustering approach for text data, and evaluate clustering performance using purity or cluster precision.

In [7]:
import nltk
# import libraries
import pandas as pd
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [8]:
# (a)	Load the dataset of Amazon reviews using pd.read_csv() and define a function parse_text() to preprocess the reviewText column

In [9]:
# Load the amazon review dataset
df = pd.read_csv('https://raw.githubusercontent.com/pycaret/pycaret/master/datasets/amazon.csv')

In [13]:
# Define a function parse_text function for text pre-processing
def parse_text(text):
    # Tokenize the text
    tokens = word_tokenize(text.lower())
    # Remove stop words
    filtered_tokens = [token for token in tokens if token not in stopwords.words('english')]
    # Lemmatize the tokens (like stemming but it brings context to the words, and links words with similar meanings to one word)
    lemmatizer = WordNetLemmatizer()
    lemmatized_tokens = [lemmatizer.lemmatize(token) for token in filtered_tokens]

    # Join the tokens back into a string
    processed_text = ' '.join(lemmatized_tokens)
    return processed_text

In [15]:
# apply the parse_text function via df
df['reviewText'] = df['reviewText'].apply(parse_text)

In [16]:
# (b) Convert the reviewText column into a list of Python strings, docs, and the positive column into a list of Python integers, y_true

In [17]:
# view each reviewText as a document and store them in a list
docs = df['reviewText'].astype(str).tolist()

In [18]:
# get the ground truth labels
y_true = df['Positive'].astype(int).tolist()

In [ ]:
# (c) Design an LDA-based clustering model using LatentDirichletAllocation and CountVectorizer

In [23]:
#  LDA (model)-based clustering
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(docs)

lda = LatentDirichletAllocation(n_components=3)
# n_components means number of topics
lda.fit(X)

LatentDirichletAllocation(n_components=3)

In [ ]:
# (d)	Get document-topic distribution and print top-5 words for the three topics.

In [25]:
# for each document, it finds the topics distribution in the document 
# Get document-topic distribution
doc_topics = lda.transform(X)
print("\nDocument-topic distribution:")
print(doc_topics)


Document-topic distribution:
[[0.02589246 0.95105134 0.0230562 ]
 [0.64389805 0.02964186 0.3264601 ]
 [0.03325426 0.03466279 0.93208295]
 ...
 [0.92860678 0.03599327 0.03539995]
 [0.01691266 0.96486393 0.01822341]
 [0.01198648 0.16754986 0.82046366]]


In [27]:
# Get feature names (words)
feature_names = vectorizer.get_feature_names_out()

# Print top words per topic
n_top_words = 5
for topic_idx, topic in enumerate(lda.components_):
    top_words = [feature_names[i] for i in topic.argsort()[-n_top_words:][::-1]]
    print(f"Topic {topic_idx}: {top_words}")

Topic 0: ['app', 'game', 'kindle', 'fire', 'free']
Topic 1: ['app', 'love', 'alarm', 'great', 'use']
Topic 2: ['app', 'game', 'get', 'like', 'great']


In [29]:
# Assign clusters (hard clustering)
clusters = doc_topics.argmax(axis=1)
print("\nDocument clusters:")
y_pred = []
for i, cluster in enumerate(clusters):
    print(f"Doc {i} -> Cluster {cluster}")
    y_pred.append(cluster)



Document clusters:
Doc 0 -> Cluster 1
Doc 1 -> Cluster 0
Doc 2 -> Cluster 2
Doc 3 -> Cluster 2
Doc 4 -> Cluster 2
Doc 5 -> Cluster 0
Doc 6 -> Cluster 2
Doc 7 -> Cluster 0
Doc 8 -> Cluster 0
Doc 9 -> Cluster 2
Doc 10 -> Cluster 1
Doc 11 -> Cluster 2
Doc 12 -> Cluster 2
Doc 13 -> Cluster 1
Doc 14 -> Cluster 1
Doc 15 -> Cluster 0
Doc 16 -> Cluster 0
Doc 17 -> Cluster 1
Doc 18 -> Cluster 1
Doc 19 -> Cluster 1
Doc 20 -> Cluster 1
Doc 21 -> Cluster 1
Doc 22 -> Cluster 2
Doc 23 -> Cluster 1
Doc 24 -> Cluster 0
Doc 25 -> Cluster 0
Doc 26 -> Cluster 1
Doc 27 -> Cluster 0
Doc 28 -> Cluster 0
Doc 29 -> Cluster 0
Doc 30 -> Cluster 0
Doc 31 -> Cluster 2
Doc 32 -> Cluster 0
Doc 33 -> Cluster 0
Doc 34 -> Cluster 0
Doc 35 -> Cluster 2
Doc 36 -> Cluster 2
Doc 37 -> Cluster 2
Doc 38 -> Cluster 0
Doc 39 -> Cluster 2
Doc 40 -> Cluster 0
Doc 41 -> Cluster 2
Doc 42 -> Cluster 2
Doc 43 -> Cluster 0
Doc 44 -> Cluster 2
Doc 45 -> Cluster 1
Doc 46 -> Cluster 0
Doc 47 -> Cluster 2
Doc 48 -> Cluster 2
Doc 49 -> 

In [31]:
# Purity Calculation Code
print(y_pred)

[1, 0, 2, 2, 2, 0, 2, 0, 0, 2, 1, 2, 2, 1, 1, 0, 0, 1, 1, 1, 1, 1, 2, 1, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 1, 0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 1, 2, 1, 2, 0, 1, 0, 0, 0, 2, 1, 0, 0, 1, 1, 2, 0, 0, 1, 2, 2, 0, 2, 2, 1, 1, 2, 0, 1, 1, 2, 2, 0, 1, 2, 2, 0, 0, 0, 1, 2, 2, 0, 2, 0, 0, 1, 0, 0, 2, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0, 0, 2, 2, 2, 1, 0, 1, 0, 0, 0, 0, 1, 2, 0, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 0, 0, 2, 0, 1, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 1, 2, 0, 1, 0, 0, 0, 0, 1, 1, 2, 0, 2, 0, 0, 2, 2, 2, 1, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 0, 2, 0, 2, 2, 0, 0, 1, 0, 0, 2, 1, 1, 0, 2, 2, 2, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 2, 2, 0, 1, 2, 2, 0, 2, 0, 2, 0, 0, 0, 1, 0, 1, 1, 2, 2, 0, 2, 2, 0, 2, 2, 1, 0, 2, 2, 2, 0, 0, 0, 0, 1, 2, 0, 0, 2, 0, 0, 0, 2, 1, 0, 1, 0, 2, 2, 2, 0, 1, 0, 2, 0, 2, 0, 2, 2, 1, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 2, 1, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 2, 1, 2, 0, 1, 2, 1, 0, 2, 2, 1, 1, 0, 2, 0, 2, 1, 1, 0, 0, 2, 0, 2, 1, 2, 

In [33]:
# (f)	Design a purity score function to evaluate the clustering performance.

In [35]:
import numpy as np
from collections import Counter

def purity_score(y_true, y_pred):
    """
    Compute clustering purity

    Parameters:
    y_true : list or array of true labels
    y_pred : list or array of cluster assignments

    Returns:
    purity : float
    """
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)

    total_correct = 0

    for cluster in np.unique(y_pred):
        # indices of points in this cluster
        indices = np.where(y_pred == cluster)[0]
        #print(indices)
        # true labels of these points
        labels = y_true[indices]
        #print(labels)
        # count most common label
        most_common_count = Counter(labels).most_common(1)[0][1]
        #print(most_common_count)
        total_correct += most_common_count

    return total_correct / len(y_true)

In [37]:
# print ground truth
y_true

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [39]:
# test function purity_score

In [41]:
#y_true = ["Yes", "Yes", "Yes", "Yes", "Yes", "Yes", "No", "No"]
purity = purity_score(y_true, y_pred)
print("Purity:", purity)

Purity: 0.76165
